/* eslint-disable max-len */

export default {
  name: 'David Sinclair',
  divider: ' · ',
  pages: {
    resume: {
      title: 'Resume',
    },
    about: {
      title: 'Personal website of David Sinclair',
    },
  },
  feed: [
    {
      type: 'thought',
      id: 'make-your-css-polished',
      title: 'Make Your CSS Polished',
      description: 'A collection of goodies for those writing CSS in JavaScript',
      date: '2017-04-20',
    },
    {
      type: 'thought',
      id: 'react-native-discovery',
      title: 'React Native Discovery',
      description: 'A series of investigations into React Native integration and libraries',
      date: '2017-04-13',
    },
    {
      type: 'thought',
      id: 'make-your-code-prettier',
      title: 'Make Your Code Prettier',
      description: 'End the days of PRs that debate formatting issues. Focus on the code!',
      date: '2017-04-03',
    },
    {
      type: 'thought',
      id: 'web-cryptography',
      title: 'Web Cryptography and Why?',
      description: 'Looking into the API used for encrypting, decrypting and when to use it',
      date: '2017-03-22',
    },
    {
      type: 'thought',
      id: 'implementing-flow',
      title: 'Implementing Flow',
      description: 'Learning and finagling Flow, a JavaScript type checker from Facebook',
      date: '2017-03-01',
    },
    {
      type: 'thought',
      id: 'aws-lambda-api-scaling',
      title: 'AWS Lambda API Scaling',
      description: 'Finding the limits using Gatling against AWS API Gateway & Lambda',
      date: '2017-02-21',
    },
    {
      type: 'thought',
      id: 'what-is-fela',
      title: 'What is this Fela?',
      description: 'Checking out one of the newer CSS-in-JavaScript kids on the block',
      date: '2017-02-07',
    },
    {
      type: 'thought',
      id: 'react-native-familiarization',
      title: 'React Native Familiarization',
      description: 'Looking to combine web apps with native apps? This is your jam',
      date: '2017-01-28',
    },
    {
      type: 'thought',
      id: 'a-first-look-at-claudia-js',
      title: 'A First Look at Claudia.JS',
      description: 'If you have used Serverless, but curious what else is out there',
      date: '2017-01-14',
    },
    {
      type: 'thought',
      id: 'serverless-framework-alternatives',
      title: 'Serverless Framework Alternatives',
      description: 'If you have used Serverless, but curious what else is out there',
      date: '2017-01-01',
    },
    {
      type: 'thought',
      id: 'the-learning-process',
      title: 'The Learning Process',
      description: 'A high-level dissection of when to use a starter-pack or doing it from scratch',
      date: '2016-08-01',
    },
    {
      type: 'project',
      id: 'pathway-genomics',
      title: 'Pathway Genomics',
      date: '2016-07-07',
      images: 5,
    },
    {
      type: 'thought',
      id: 'some-development-notes',
      title: 'Some Development Notes',
      description: 'A compilation of notes and thoughts after a year of becoming more closely aligned with the world of JavaScript development',
      date: '2016-04-04',
    },
    {
      type: 'project',
      id: 'elevated',
      title: 'Elevated',
      external: 'http://elevated.com',
      date: '2015-01-22',
      images: 3,
    },
    {
      type: 'thought',
      id: 'a-new-cell-phone',
      title: 'A New Cell Phone',
      description: 'Documenting a transition, including pains and gains, from a paying phone service to a free, via exciting apps and the help of the giant, Google',
      date: '2013-04-12',
    },
    {
      type: 'thought',
      id: 'what-we-need',
      title: 'What We Need',
      description: 'A comment on the world of options we live in and the direction I hope our behaviors will move toward',
      date: '2012-08-19',
    },
    {
      type: 'project',
      id: 'art-tiles-by-carla',
      title: 'Art Tiles by Carla',
      external: 'http://arttilesbycarla.com',
      date: '2012-01-21',
      images: 1,
    },
    {
      type: 'project',
      id: 'travel-to-go',
      title: 'Travel To Go',
      date: '2012-01-21',
      images: 1,
    },
    {
      type: 'project',
      id: 'words-for-sense',
      title: 'Words for Sense',
      date: '2012-01-21',
      images: 1,
    },
    {
      type: 'project',
      id: 'man-moves',
      title: 'Man Moves',
      date: '2012-01-21',
      images: 1,
    },
    {
      type: 'thought',
      id: 'simplicity-and-complexity',
      title: 'Simplicity & Complexity',
      description: 'A partial review of a book that can shape your perspective on design, life, and everything in between',
      date: '2011-06-07',
    },
    {
      type: 'project',
      id: 'dd-studio',
      title: 'DD Studio',
      date: '2011-01-21',
      images: 2,
    },
  ],
};
